import sqlite3
conn=sqlite3.connect('test.db')
print("Opened Database Successfully")
conn.execute("UPDATE COMPANY set SALARY=25000.00 where ID=1")
conn.commit()
print("Total Number of Row Update",conn.total_changes)
cursor=conn.execute("SELECT id, name,age, address, salary from COMPANY")
for row in cursor:
    print("ID = ", row[0])
    print("NAME = ", row[1])
    print("AGE = ", row[2])
    print("ADDRESS = ", row[3])
    print("SALARY = ", row[4])
print("Operation Done Successfully")
conn.close()
