name: deliwer_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  circular_check_box: ^1.0.4
  flutter_credit_card: ^0.1.3
  credit_card_input_form: ^2.1.0
  confetti: ^0.5.4+1
  search_widget: ^1.0.2
  toast: ^0.1.5
  badges: ^1.1.4
  dio: ^3.0.10
  http: ^0.12.2
  progress_dialog: ^1.2.4
  email_validator: '^1.0.5'
  url_launcher: ^5.7.10
  flutter_phone_direct_caller: ^1.0.1
  geolocator: ^6.1.12
  geocoding: ^1.0.5
  video_player: ^1.0.1
  geocoder: ^0.2.1
  google_maps_flutter: ^1.0.6
  awesome_card: ^1.1.0
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.3+1
  scratcher: ^1.4.0
  firebase_core: ^0.5.2+1
  sliding_up_panel: ^1.0.2
  connectivity: ^2.0.2
  awesome_dialog: ^1.2.1
  webview_flutter: ^1.0.7
  flip_card: ^0.4.4
  share: ^0.6.5+4
  pdf: ^1.12.0
  web_socket_channel: ^1.1.0
  group_radio_button: ^1.0.1
  image_picker: ^0.6.7+14
  in_app_review: ^1.0.4
  path_provider: ^1.6.24
  month_picker_dialog:
    git: 
      url: https://github.com/hmkrivoj/month_picker_dialog.git
  firebase_messaging: ^7.0.3
  dotted_border: ^1.0.7
  lottie: ^0.7.0+1
  contact_picker: ^0.0.2
  assorted_layout_widgets: ^3.0.0
  auto_size_text: ^2.1.0
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  store_redirect: ^1.0.2
  open_appstore: ^1.0.2
  countdown: ^0.1.0
  flutter_polyline_points: ^0.2.4
  dash_chat: ^1.1.9
  flutter_rating_bar: ^3.2.0+1
  flutter_datetime_picker:
    git:
      url: https://github.com/espresso3389/flutter_datetime_picker

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/Video/background_video.mp4
      - assets/images/loading.gif
      - assets/images/camera.png
      - assets/Video/deliver_splash.mp4
      - assets/animations/lottie/ready.json
      - assets/images/destination_map_marker.png
      - assets/images/logo.png
      - assets/images/app_icon.png
      - assets/images/refer_img.jpeg
      - assets/images/refer_img_1.jpg
      - assets/images/need_help_agent.png
      - assets/images/need_help_req.png
      - assets/images/markerImage.png
  #     - assets/images/logo.jpg
  #     - assets/images/signup.png
  #     - assets/images/splash.jpeg
  #     - assets/images/splash1.jpg
  #     - assets/images/verify.jpeg
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf 
        

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
