package com.ali.mapapps.Util

import android.content.Context
import android.location.Geocoder
import android.net.ConnectivityManager
import java.io.IOException
import java.text.SimpleDateFormat
import java.util.*
import kotlin.collections.HashMap

class Helper {
    companion object{
        fun isConnected(context: Context): Boolean {
            val connectivityManager = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
            val networkInfo = connectivityManager.activeNetworkInfo
            if(networkInfo != null)
                return  networkInfo!=null && networkInfo.isConnectedOrConnecting
            return false
        }

        fun getDate():String{
            var date = ""
            val calendar = Calendar.getInstance()
            val today_date = calendar.time.toString()
            val day_month = today_date.subSequence(0,11).toString()
            try {
                val _24HourTime = today_date.subSequence(11,19).toString()
                val _24HourSDF = SimpleDateFormat("HH:mm")
                val _12HourSDF = SimpleDateFormat("hh:mm a")
                val _24HourDt: Date = _24HourSDF.parse(_24HourTime)
                date = day_month+" "+_12HourSDF.format(_24HourDt).toUpperCase()
            } catch (e: Exception) {
                e.printStackTrace()
            }
            return date
        }

        fun kelvintoCelcius(kelvin:Double):String{
            val celcius = kelvin - 273.15
            return celcius.toString()
        }

        fun getCountry(countryCode:String):String?{
            val mapCountry = HashMap<String,String>()
            mapCountry.put("af", "Afghanistan")
            mapCountry.put("al", "Albania")
            mapCountry.put("dz", "Algeria")
            mapCountry.put("as", "American Samoa")
            mapCountry.put("ad", "Andorra")
            mapCountry.put("ao", "Angola")
            mapCountry.put("ai", "Anguilla")
            mapCountry.put("aq", "Antarctica")
            mapCountry.put("ag", "Antigua and Barbuda")
            mapCountry.put("ar", "Argentina")
            mapCountry.put("am", "Armenia")
            mapCountry.put("aw", "Aruba")
            mapCountry.put("au", "Australia")
            mapCountry.put("at", "Austria")
            mapCountry.put("az", "Azerbaijan")
            mapCountry.put("bs", "Bahamas")
            mapCountry.put("bh", "Bahrain")
            mapCountry.put("bd", "Bangladesh")
            mapCountry.put("bb", "Barbados")
            mapCountry.put("by", "Belarus")
            mapCountry.put("be", "Belgium")
            mapCountry.put("bz", "Belize")
            mapCountry.put("bj", "Benin")
            mapCountry.put("bm", "Bermuda")
            mapCountry.put("bt", "Bhutan")
            mapCountry.put("bo", "Bolivia")
            mapCountry.put("ba", "Bosnia And Herzegovina")
            mapCountry.put("bw", "Botswana")
            mapCountry.put("br", "Brazil")
            mapCountry.put("io", "British Indian Ocean Territory")
            mapCountry.put("vg", "British Virgin Islands")
            mapCountry.put("bn", "Brunei Darussalam")
            mapCountry.put("bg", "Bulgaria")
            mapCountry.put("bf", "Burkina Faso")
            mapCountry.put("bi", "Burundi")
            mapCountry.put("kh", "Cambodia")
            mapCountry.put("cm", "Cameroon")
            mapCountry.put("ca", "Canada")
            mapCountry.put("cv", "Cape Verde")
            mapCountry.put("ky", "Cayman Islands")
            mapCountry.put("cf", "Central African Republic")
            mapCountry.put("td", "Chad")
            mapCountry.put("cl", "Chile")
            mapCountry.put("cn", "China")
            mapCountry.put("cx", "Christmas Island")
            mapCountry.put("cc", "Cocos (keeling) Islands")
            mapCountry.put("co", "Colombia")
            mapCountry.put("km", "Comoros")
            mapCountry.put("ck", "Cook Islands")
            mapCountry.put("cr", "Costa Rica")
            mapCountry.put("hr", "Croatia")
            mapCountry.put("cu", "Cuba")
            mapCountry.put("cy", "Cyprus")
            mapCountry.put("cz", "Czech Republic")
            mapCountry.put("ci", "Côte D'ivoire")
            mapCountry.put("cd", "Democratic Republic of the Congo")
            mapCountry.put("dk", "Denmark")
            mapCountry.put("dj", "Djibouti")
            mapCountry.put("dm", "Dominica")
            mapCountry.put("do", "Dominican Republic")
            mapCountry.put("ec", "Ecuador")
            mapCountry.put("eg", "Egypt")
            mapCountry.put("sv", "El Salvador")
            mapCountry.put("gq", "Equatorial Guinea")
            mapCountry.put("er", "Eritrea")
            mapCountry.put("ee", "Estonia")
            mapCountry.put("et", "Ethiopia")
            mapCountry.put("fk", "Falkland Islands (malvinas)")
            mapCountry.put("fo", "Faroe Islands")
            mapCountry.put("fj", "Fiji")
            mapCountry.put("fi", "Finland")
            mapCountry.put("fr", "France")
            mapCountry.put("gf", "French Guiana")
            mapCountry.put("pf", "French Polynesia")
            mapCountry.put("ga", "Gabon")
            mapCountry.put("gm", "Gambia")
            mapCountry.put("ge", "Georgia")
            mapCountry.put("de", "Germany")
            mapCountry.put("gh", "Ghana")
            mapCountry.put("gi", "Gibraltar")
            mapCountry.put("gr", "Greece")
            mapCountry.put("gl", "Greenland")
            mapCountry.put("gd", "Grenada")
            mapCountry.put("gp", "Guadeloupe")
            mapCountry.put("gu", "Guam")
            mapCountry.put("gt", "Guatemala")
            mapCountry.put("gg", "Guernsey")
            mapCountry.put("gn", "Guinea")
            mapCountry.put("gw", "Guinea-Bissau")
            mapCountry.put("gy", "Guyana")
            mapCountry.put("ht", "Haiti")
            mapCountry.put("va", "Holy See (Vatican City State)")
            mapCountry.put("hn", "Honduras")
            mapCountry.put("hk", "Hong Kong")
            mapCountry.put("hu", "Hungary")
            mapCountry.put("is", "Iceland")
            mapCountry.put("in", "India")
            mapCountry.put("id", "Indonesia")
            mapCountry.put("ir", "Iran")
            mapCountry.put("iq", "Iraq")
            mapCountry.put("ie", "Ireland")
            mapCountry.put("im", "Isle Of Man")
            mapCountry.put("il", "Israel")
            mapCountry.put("it", "Italy")
            mapCountry.put("jm", "Jamaica")
            mapCountry.put("jp", "Japan")
            mapCountry.put("je", "Jersey")
            mapCountry.put("jo", "Jordan")
            mapCountry.put("kz", "Kazakhstan")
            mapCountry.put("ke", "Kenya")
            mapCountry.put("ki", "Kiribati")
            mapCountry.put("xk", "Kosovo")
            mapCountry.put("kw", "Kuwait")
            mapCountry.put("kg", "Kyrgyzstan")
            mapCountry.put("la", "Lao People's Democratic Republic")
            mapCountry.put("lv", "Latvia")
            mapCountry.put("lb", "Lebanon")
            mapCountry.put("ls", "Lesotho")
            mapCountry.put("lr", "Liberia")
            mapCountry.put("ly", "Libya")
            mapCountry.put("li", "Liechtenstein")
            mapCountry.put("lt", "Lithuania")
            mapCountry.put("lu", "Luxembourg")
            mapCountry.put("mo", "Macao Sar China")
            mapCountry.put("mk", "Macedonia")
            mapCountry.put("mg", "Madagascar")
            mapCountry.put("mw", "Malawi")
            mapCountry.put("my", "Malaysia")
            mapCountry.put("mv", "Maldives")
            mapCountry.put("ml", "Mali")
            mapCountry.put("mt", "Malta")
            mapCountry.put("mh", "Marshall Islands")
            mapCountry.put("mq", "Martinique")
            mapCountry.put("mr", "Mauritania")
            mapCountry.put("mu", "Mauritius")
            mapCountry.put("yt", "Mayotte")
            mapCountry.put("mx", "Mexico")
            mapCountry.put("fm", "Micronesia")
            mapCountry.put("md", "Moldova")
            mapCountry.put("mc", "Monaco")
            mapCountry.put("mn", "Mongolia")
            mapCountry.put("me", "Montenegro")
            mapCountry.put("ms", "Montserrat")
            mapCountry.put("ma", "Morocco")
            mapCountry.put("mz", "Mozambique")
            mapCountry.put("mm", "Myanmar (Burma)")
            mapCountry.put("na", "Namibia")
            mapCountry.put("nr", "Nauru")
            mapCountry.put("np", "Nepal")
            mapCountry.put("nl", "Netherlands")
            mapCountry.put("nc", "New Caledonia")
            mapCountry.put("nz", "New Zealand")
            mapCountry.put("ni", "Nicaragua")
            mapCountry.put("ne", "Niger")
            mapCountry.put("ng", "Nigeria")
            mapCountry.put("nu", "Niue")
            mapCountry.put("nf", "Norfolk Island")
            mapCountry.put("kp", "North Korea")
            mapCountry.put("mp", "Northern Mariana Islands")
            mapCountry.put("no", "Norway")
            mapCountry.put("om", "Oman")
            mapCountry.put("pk", "Pakistan")
            mapCountry.put("pw", "Palau")
            mapCountry.put("ps", "Palestinian Territory, Occupied")
            mapCountry.put("pa", "Panama")
            mapCountry.put("pg", "Papua New Guinea")
            mapCountry.put("py", "Paraguay")
            mapCountry.put("pe", "Peru")
            mapCountry.put("ph", "Philippines")
            mapCountry.put("pn", "Pitcairn Islands")
            mapCountry.put("pl", "Poland")
            mapCountry.put("pt", "Portugal")
            mapCountry.put("pr", "Puerto Rico")
            mapCountry.put("qa", "Qatar")
            mapCountry.put("cg", "Republic of the Congo - Brazzaville")
            mapCountry.put("ro", "Romania")
            mapCountry.put("ru", "Russian Federation")
            mapCountry.put("rw", "Rwanda")
            mapCountry.put("re", "Réunion")
            mapCountry.put("bl", "Saint Barthélemy")
            mapCountry.put("sh", "Saint Helena")
            mapCountry.put("kn", "Saint Kitts & Nevis")
            mapCountry.put("lc", "Saint Lucia")
            mapCountry.put("mf", "Saint Martin")
            mapCountry.put("pm", "Saint Pierre & Miquelon")
            mapCountry.put("vc", "Saint Vincent & The Grenadines")
            mapCountry.put("ws", "Samoa")
            mapCountry.put("sm", "San Marino")
            mapCountry.put("st", "Sao Tome & Principe")
            mapCountry.put("sa", "Saudi Arabia")
            mapCountry.put("sn", "Senegal")
            mapCountry.put("rs", "Serbia")
            mapCountry.put("sc", "Seychelles")
            mapCountry.put("sl", "Sierra Leone")
            mapCountry.put("sg", "Singapore")
            mapCountry.put("sx", "Sint Maarten")
            mapCountry.put("sk", "Slovakia")
            mapCountry.put("si", "Slovenia")
            mapCountry.put("sb", "Solomon Islands")
            mapCountry.put("so", "Somalia")
            mapCountry.put("za", "South Africa")
            mapCountry.put("gs", "South Africa (South Georgia & South Sandwich Islands)")
            mapCountry.put("kr", "South Korea")
            mapCountry.put("ss", "South Sudan")
            mapCountry.put("es", "Spain")
            mapCountry.put("lk", "Sri Lanka")
            mapCountry.put("sd", "Sudan")
            mapCountry.put("sr", "Suriname")
            mapCountry.put("sz", "Swaziland")
            mapCountry.put("se", "Sweden")
            mapCountry.put("ch", "Switzerland")
            mapCountry.put("sy", "Syrian Arab Republic")
            mapCountry.put("tw", "Taiwan")
            mapCountry.put("tj", "Tajikistan")
            mapCountry.put("tz", "Tanzania")
            mapCountry.put("th", "Thailand")
            mapCountry.put("tl", "Timor-Leste")
            mapCountry.put("tg", "Togo")
            mapCountry.put("tk", "Tokelau")
            mapCountry.put("to", "Tonga")
            mapCountry.put("tt", "Trinidad & Tobago")
            mapCountry.put("tn", "Tunisia")
            mapCountry.put("tr", "Turkey")
            mapCountry.put("tm", "Turkmenistan")
            mapCountry.put("tc", "Turks & Caicos Islands")
            mapCountry.put("tv", "Tuvalu")
            mapCountry.put("ug", "Uganda")
            mapCountry.put("ua", "Ukraine")
            mapCountry.put("ae", "United Arab Emirates")
            mapCountry.put("gb", "United Kingdom")
            mapCountry.put("us", "United States")
            mapCountry.put("uy", "Uruguay")
            mapCountry.put("vi", "US Virgin Islands")
            mapCountry.put("uz", "Uzbekistan")
            mapCountry.put("vu", "Vanuatu")
            mapCountry.put("ve", "Venezuela")
            mapCountry.put("vn", "Vietnam")
            mapCountry.put("wf", "Wallis And Futuna")
            mapCountry.put("ye", "Yemen")
            mapCountry.put("zm", "Zambia")
            mapCountry.put("zw", "Zimbabwe")
            mapCountry.put("ax", "Åland Islands")
            return mapCountry.get(countryCode.toLowerCase())
        }

        fun getLocation(context:Context,latitude:Double,longitude:Double):String{
            try{
                val geocoder = Geocoder(context, Locale.getDefault())
                val addresses = geocoder.getFromLocation(latitude,longitude,3)
                val city = addresses[0].locality
                val state = addresses[0].adminArea
                val postalCode = addresses[0].postalCode
                val district = addresses[0].subAdminArea
                val countryCode = addresses[0].countryCode
                val countryName = addresses[0].countryName
                return city+", "+state
            }catch(e: IOException) {
                return "Couldn't get your Location"
            }
        }
    }
}